### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by felipemanga** [eried/ArduboyCollection#10]
Would it be possible to add "Access-Control-Allow-Origin:*" to the repo.json HTTP headers?

Without it, ProjectABE can't access the repo directly and depends on the cors-anywhere service, which isn't meant for production use. 

For the hex files, I'm using https://gitcdn.xyz/, which should be OK.

**Comment by eried** [comment]
You can change whatever you need, just check .admin folder and do a pull request 👍 

This is probably the file you need to edit
https://github.com/eried/ArduboyCollection/blob/master/.admin/public_html/arduboy/template.html

**Comment by felipemanga** [comment]
I don't think I can change this... I'm talking about an nginx config for this file: http://arduboy.ried.cl/repo.json

Right now it responds with:
HTTP/1.1 200 OK
Server: nginx admin
Date: Wed, 20 Dec 2017 21:42:35 GMT
Content-Type: application/json
Content-Length: 164734
Connection: keep-alive
Last-Modified: Tue, 19 Dec 2017 23:33:33 GMT
ETag: "5621e1-2837e-560b9e5224d40"
Accept-Ranges: bytes
X-Cache: HIT from Backend

Since there's no "Access-Control-Allow-Origin:*" header, ProjectABE can't access it and has to use a proxy.
see: https://enable-cors.org/server_nginx.html

**Comment by eried** [comment]
Oh... It is a crappy mochahost server, I am not sure either. I will try tomorrow to check cpanel settings

**Comment by eried** [comment]
Can you check now? I added a `.htaccess` with:

```
<FilesMatch "\.(json)$">
    <IfModule mod_headers.c>
        SetEnvIf Origin "http(s)?://(www\.)?(felipemanga.github.io)$" AccessControlAllowOrigin=$0
        Header add Access-Control-Allow-Origin %{AccessControlAllowOrigin}e env=AccessControlAllowOrigin
    </IfModule>
</FilesMatch>
```

Not really sure if that will work in my server. I do not have much more control.

**Comment by felipemanga** [comment]
Hey, sorry I took so long to reply.

It didn't work... now I get an error due to the use of HTTP instead of HTTPS.
I wasn't aware of CORS requiring HTTPS. >_<

Thanks for trying, though :)

**Comment by eried** [comment]
in that case (my hosting plan does not support https) I can push it to the repo here in github. Will that work if it is updated programmatically? (my website can then read that file instead of the local one too)

**Comment by eried** [comment]
... or maybe to another service so I do not have to deal login in to git in php, any suggestion?

**Comment by alexgleason** [comment]
We could try a different host. It's just a static site, so you could host it with [surge](https://surge.sh) for free. They [allow CORS](https://surge.sh/help/enabling-cross-origin-resource-sharing) by creating a simple empty file in the root directory.

You'd have to run the PHP stuff on your own machine to generate the HTML output, then you could just upload it straight to surge.

**Comment by eried** [comment]
I think this is already solved because everything runs on github pages now :)
