### ISSUE TITLE
Include game license on page and allow filtering by license

### ISSUE THREAD

**Issue by alexgleason** [eried/ArduboyCollection#28]
Hi, thanks for building this nice library!

I'd like to discover only FLOSS games, and it's unfortunate that many Arduboy games don't have a license. This essentially renders them proprietary, even though the source is available.

It would be much easier if I could see which games are FLOSS right on the front page and filter them by this.

I'd be willing to send a PR with the license added to each game if you want to do this.

**Comment by eried** [comment]
Sure thing. Any proposal for displaying the licenses?

**Comment by alexgleason** [comment]
Maybe something like this?

```html
<p class="license">
    GPL-3.0 <i class="fa fa-balance-scale"></i>
</p>
```

![screenshot from 2018-02-11 18 42 09](https://user-images.githubusercontent.com/3639540/36080250-4c5589d0-0f5b-11e8-8647-f1d7345f8c4d.png)

**Comment by eried** [comment]
Sounds good. Go ahead adding the licenses :)

**Comment by alexgleason** [comment]
Okay, I'm adding a `license` key to each .ini file, setting it equal to the relevant [SPDX license identifier](https://spdx.org/licenses/). For instance:

```
title=Choplifter
date=2018-02-01T13:00:00Z
author=Simon Holmes (filmote)
description=The classic Choplifter game for the Arduboy!
hex=https://raw.githubusercontent.com/filmote/Choplifter/master/distibutable/Choplifter.hex
license=BSD-3-Clause
```

I'm skipping the `license` key entirely for games which don't have one. Let me know if that sounds good.

**Comment by eried** [comment]
Sound perfect! I will add the new field soon, thanks a lot
