### ISSUE TITLE
Use poster for video banner before it loads

### ISSUE THREAD

**Issue by alexgleason** [eried/ArduboyCollection#29]
I noticed there's an unused `banner.jpg` which would serve this purpose. Basically as the video is loading, it would show the image behind the unloaded video instead of a gray background.

See here: https://www.w3schools.com/TAgs/att_video_poster.asp

**Comment by eried** [comment]
The template comes from https://templated.co and the banner.jpg (I think) is for some devices that do not support the video, not for a preloading but I can check into that.

Anyway, the front-end code is also available here: https://github.com/eried/ArduboyCollection/tree/master/.admin/public_html/arduboy ... just if you are really bored one day 🤣

**Comment by alexgleason** [comment]
The template uses some javascript to insert the video, making it a little annoying to change which is why I didn't do this in the last update. If I get a chance I'll look at this again in my next PR.
