### ISSUE TITLE
GPL games must have source code distributed with them

### ISSUE THREAD

**Issue by alexgleason** [eried/ArduboyCollection#32]
So, I didn't realize this a few days ago when I started this process, but today I was reading about the GPL and came upon this fact:

>**I downloaded just the binary from the net. If I distribute copies, do I have to get the source and distribute that too?**
>
>Yes. The general rule is, if you distribute binaries, you must distribute the complete corresponding source code too. The exception for the case where you received a written offer for source code is quite limited.

https://www.gnu.org/licenses/gpl-faq.html#UnchangedJustBinary

This means that distributing the .hex files as we are may actually violate the terms of the GPL license itself. We have to distribute the source code in the repo for these games as well.

I'm not sure if linking to the source code on a different server is enough. Perhaps we should find this out.

**Comment by eried** [comment]
That is quite limiting. How can the "transfer to my Arduboy" button follow that rule?

For the 'download hex" button I can make a zip that contains the license inside.

**Comment by alexgleason** [comment]
My interpretation is that as long as a "download source" button exists on the page for GPL licensed games, we're good.

My concern is specifically about whether that download needs to come from the same server. I think you could argue that by hosting the .hex file on your server you are distributing a binary, but by *not* hosting the source code you are *not* distributing the source code, someone else is and you're just linking me to it.

Another interpretation is that because you're linking to them, you *are* distributing the source code.

So what does it mean to "distribute" the code? Does it have to be on the same server or do you just have to point people in the right direction from the same place? I don't really know.

**Comment by eried** [comment]
I think maybe downloading the remote repo and attaching that would be enough (with the LICENSE and all), so the link can stay but I also host a snapshot of the contents, what do you think?

**Comment by alexgleason** [comment]
I think that would be great, though I'm concerned about checking so many large files into the repo. It's already quite slow to download with all the .hex files.

**Comment by eried** [comment]
Or maybe make a new organization in github and fork all the games. I guess that will work

**Comment by eried** [comment]
Back to this issue again: 
https://github.com/ArduboyCollection

Those forks are the linked ones in the repo now:
https://github.com/eried/ArduboyCollection/commit/06a97089252a9da083c09cdb81c7da9ea4c52e48

Do you think that actually solves the issue?

**Comment by alexgleason** [comment]
Sorry, but I don't think it does. I should have responded sooner. Legally speaking, I think GitHub is actually distributing this source code, not you, even though you control the fork (to some degree) you still don't control the server it's stored on. I'm not a lawyer, but this is my interpretation based on the little that I know.

I'm still not 100% sure this is actually an issue. There are several ways to interpret the license text. I've been meaning to reach out to some peers more knowledgeable than me on the issue. Once I do we can know for certain.

Assuming it is a problem, I have a few ideas.

1. Possibly, do not host .hex files in this repo for GPL games, link to them from the GitHub releases page of each repo. This makes GitHub the host of both the compiled binaries and the source code, so I think merely linking in to them doesn't make you liable. You don't need to link to a fork for this, and linking to the original source is likely better because the forks may not be updated.

2. Alternatively, distribute the source and .hex files directly from your server. Or, to prevent the git repo from growing massive, we could store the files elsewhere, like Amazon S3, and link to them from the repo.

I don't have a clear course of action yet, but I'm thinking about it in the back of my mind.

**Comment by eried** [comment]
Ok I will ask around, I have little to no knowledge either

**Comment by redhog** [comment]
Hope is ok that I pitch in here: As far as I understan, as both the binary files and their corresponding source are distributed on github, under the same github user, there should be no license problem. The GPL doesn't specify that you can't outsource hosting the source. It just specifies you have to distribute it together with the binaries. It does not however specify a certain directory structure (or in this case, repo structure). The argreement you have with github for hosting both binaries and source is the same, so that should be fine. As far as who is distributing, I'm pretty sure it's @eried not github, as @eried has a contract with github for doing that (that clicked yes to when signing up).

Actually storing the binaries on a separate server could be problematic, as then that server could go down for a prolonged period without github going down, and then @eried  would be in breach...

**Comment by eried** [comment]
@alexgleason does that answer satisfies you?

**Comment by alexgleason** [comment]
Yes, I took a second to actually read the GPL. Here's what it says in section 6.d:

>Convey the object code by offering access from a designated place (gratis or for a charge), and offer equivalent access to the Corresponding Source in the same way through the same place at no further charge. You need not require recipients to copy the Corresponding Source along with the object code. If the place to copy the object code is a network server, **the Corresponding Source may be on a different server** (operated by you or a third party) that supports equivalent copying facilities, **provided you maintain clear directions next to the object code saying where to find the Corresponding Source.** Regardless of what server hosts the Corresponding Source, you remain obligated to ensure that it is available for as long as needed to satisfy these requirements.

In other words, there was never an issue to begin with. I'm sorry for the confusion I caused.
