### ISSUE TITLE
Add TEAM a.r.g. games

### ISSUE THREAD

**Issue by alexgleason** [eried/ArduboyCollection#37]
I noticed TEAM a.r.g.'s games aren't in the repo. They distribute their games in .arduboy format, which may be why, but they're just glorified ZIP files which contain the .hex within. I've started working on extracting the .hex's and adding them to this repo but wanted to make a note in case I don't get around to doing them all.

http://www.team-arg.org/games.html (Arduboy games have a little gameboy icon)

**Comment by eried** [comment]
My uploader supports those files, I haven't published their games because they do not want to be in the repo. Same as Circuit Dude game

**Comment by eried** [comment]
And including support in the repo for arduboy files is also trivial, but I haven't had any reason to do that

**Comment by alexgleason** [comment]
Um, hm... I mean, the MIT license allows you to redistribute the content.

For example: https://github.com/TEAMarg/ID-40-VIRUS-LQP-79/blob/master/LICENSE

>Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, **publish**, **distribute**, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so

Where did they ask not to publish the games in your repo?

**Comment by eried** [comment]
Via messages in the Arduboy forum

**Comment by alexgleason** [comment]
Interesting. Well, I'm more confident about interpreting the MIT than I am the GPL. MIT is a very simple license which explicitly allow redistribution, and that's part of what makes a game libre.

If it was just a personal ask, you may as well honor it, although I'd like to follow up with them and see if they'll change their minds. I don't think they can stop people from redistributing their game once people have received a copy of the license.

**Comment by eried** [comment]
Yeah, but as you checked via PM, they do not want the games here. Not really sure what is the harm, or why they choose MIT but I guess that closes this issue.
