### ISSUE TITLE
Add the number of registered games to the main page

### ISSUE THREAD

**Issue by Pharap** [eried/ArduboyCollection#50]
I recently made [a comment](https://community.arduboy.com/t/im-gonna-get-my-arduboy-for-my-birthday/5666/10) on the Arduboy forums and it got me thinking.
It would be nice if the main page displayed how many games there are in the repo.

**Comment by eried** [comment]
Yes, sounds good. Any proposed solution? (aesthetically-wise https://github.com/eried/ArduboyCollection/tree/master/.admin/public_html/arduboy)

**Comment by Pharap** [comment]
Unfortunately I haven't used HTML in years, and I haven't touched PHP since college, so I wouldn't know how to implement it.

Aesthetically though, I think it should either be in the subheading, e.g. "A curated list of games for the Arduboy, 123 games registered", or as another bullet point.

**Comment by eried** [comment]
I will add it soon. For the moment, if you open http://arduboy.ried.cl/repo.json in FF, you will see that there are 186 games :)
