### ISSUE TITLE
Is source.url actually being used?

### ISSUE THREAD

**Issue by Pharap** [eried/ArduboyCollection#68]
When making an update to Minesweeper I looked on the main website to see where `source.url` is being used and it seems that it isn't being used?

All of 'download hex', 'play in emulator' and 'upload to my arduboy' use the hex uploaded to the repo.
The url provided in `source.url` doesn't appear to be used at all?

**Comment by eried** [comment]
Yes, the link is in the name of the author.

**Comment by eried** [comment]
Oh, `source.url` is for the sourcecode, if you want to link the hex file use `hex=something` inside `game.ini`

**Comment by Pharap** [comment]
I see that now, I must have got some stuff muddled when I originally uploaded. I'll fix that now.
I don't know what using `hex=` in `game.ini` would actually do, so I don't think I'll bother.

**Comment by eried** [comment]
It will use that for the links you mentioned here https://github.com/eried/ArduboyCollection/issues/68#issue-352658004 instead of the local hex (example if you already keep your .hex file in your own repo and don't want to care updating it here)
