### ISSUE TITLE
More info in JSON

### ISSUE THREAD

**Issue by felipemanga** [eried/ArduboyCollection#7]
Hey,

I needed working sourceUrls so I started using an edited version of your JSON file.
There's still a bunch missing, but it's a start. Would you like to merge it back?

https://felipemanga.github.io/ProjectABE/repo-eried.json

**Comment by eried** [comment]
Sure thing, but first I will have to add more info to the repo, because that json file is generated from there

**Comment by eried** [comment]
Hey @felipemanga how did you added the author? I am thinking on making a json for each folder with the missing data so it can be autogenerated (plus I need to add the date to sort them by "new")

**Comment by felipemanga** [comment]
I opened the json in emacs and did a search+replace to create the empty author/sourceUrl keys.
Then I manually clicked through some of the urls to get the actual data.
A JSON in each folder seems like a good idea.

**Comment by eried** [comment]
OK, cool I will use your JSON as the starting point to create the individual game metadata files. Maybe a simpler config file will do the trick:
```

title=game title
author=...
```

(because I want to keep the files stupid simple)

**Comment by eried** [comment]
OK I fixed the json https://github.com/eried/ArduboyCollection/commit/2211355d0a097c205111594910ea53c310b84222

I will have to eventually add more authors and source url links. You are welcome to do that if you want
